name: Testing
on:
  push:
    branches:
      - "*"

jobs:
  run-checks:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: oltp_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports:
          - 5432:5432


    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup- Python
        uses: actions/checkout@v4
        with: 
          python-version: '3.11'
      
      - name: Install requirements
        run: make requirements


      - name: Make dev-setup
        run: make dev-setup

      - name: Make security-test
        run: make security-test
  
      - name: Make run-flake
        run: make run-flake

      - name: Create Test Database
        run: psql -h localhost -U postgres -d oltp_test -f tests/test_extraction/data/test-extraction.sql
        env:
          PGPASSWORD: postgres

      - name: Create 2nd Test Database
        run: psql -h localhost -U postgres -d oltp_test -f tests/test_storage/data/test-insertion.sql
        env:
              PGPASSWORD: postgres

              
      - name: Make unit-test1
        run: make unit-test1
        env:
          PGPASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: oltp_test
          TEST_DATABASE: oltp_test
          PASSWORD: postgres
          USER: postgres

      - name: Make unit-test2
        run: make unit-test2  

      - name: Make unit-test3
        run: make unit-test3
        env:
          PGPASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: oltp_test
          TEST_DATA_WAREHOUSE: oltp_test
          PASSWORD: postgres
          USER: postgres

      - name: Make check-coverage1
        run: make check-coverage1
        env:
          PGPASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: oltp_test
          TEST_DATABASE: oltp_test
          PASSWORD: postgres
          USER: postgres
      
      - name: Make check-coverage2
        run: make check-coverage2
     
      - name: Make check-coverage3
        run: make check-coverage3
        env:
            PGPASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: oltp_test
            TEST_DATA_WAREHOUSE: oltp_test
            PASSWORD: postgres
            USER: postgres
      
    
    

